:x

diff --git a/getit b/getit
--- a/getit
+++ b/getit
@@ -4,54 +4,53 @@
 install_packages() {
   sudo apt autoremove -y 
   sudo apt update
-  sudo apt install -y "$@"
   sudo apt install tmux gpg gcc make gettext unzip cmake build-essential python3-neovim jq wget curl apt-file python3-dev python3-pip tzdata dconf-cli uuid-runtime inetutils-ping rclone pkg-config libtool -y
 }
 
 # Function to handle git operations
-git_operations() {
-  git config --global user.name "regular bill"
-  git config --global user.email "regularbill@bill.com"
+#git_operations() {
+#  git config --global user.name "regular bill"
+#  git config --global user.email "regularbill@bill.com"
 
   # Check for access to the 'winslowb' GitHub repository
-  if gh repo view https://github.com/winslowb/dotfiles.git &>/dev/null; then
-    echo "You have access to the winslowb GitHub repository."
-  else
-    echo "You don't have access to the winslowb GitHub repository. Setting up authentication..."
-    gh auth login
-  fi
-}
+#  if gh repo view https://github.com/winslowb/dotfiles.git &>/dev/null; then
+#    echo "You have access to the winslowb GitHub repository."
+#  else
+#    echo "You don't have access to the winslowb GitHub repository. Setting up authentication..."
+#    gh auth login
+#  fi
+#}
 
 # Function to create directory if it doesn't exist
-create_directory() {
-  [ ! -d "$1" ] && mkdir -p "$1"
-}
+#create_directory() {
+#  [ ! -d "$1" ] && mkdir -p "$1"
+#}
 
 # Initial package updates and installs
 
 
 # GitHub CLI setup
-if ! type -p curl > /dev/null; then
-  install_packages curl
-fi
+#if ! type -p curl > /dev/null; then
+#  install_packages curl
+#fi
 
-{
-  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
-  sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
-  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
-  sudo apt update
-  install_packages gh
-} || {
-  echo "GitHub CLI setup failed."
-  exit 1
-}
+#{
+#  curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
+#  sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
+#  echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
+#  sudo apt update
+#  install_packages gh
+#} || {
+#  echo "GitHub CLI setup failed."
+#  exit 1
+#}
 
 # Directory setup
 create_directory "$HOME/projects"
 create_directory "$HOME/.local/bin"
 
-cd $HOME || exit
-git_operations
+#cd $HOME || exit
+#git_operations
 
 # Function to reload shell environment
 reload_shell() {
@@ -120,15 +119,15 @@ cd $HOME/projects || exit
 }
 
 # JIRA CLI Setup
-cd $HOME/projects || exit
-{
-  wget https://github.com/ankitpokhrel/jira-cli/releases/download/v1.3.0/jira_1.3.0_linux_arm64.tar.gz
-  tar -xzvf jira_1.3.0_linux_arm64.tar.gz
-} || {
-  echo "JIRA CLI setup failed."
-  exit 1
-}
+#cd $HOME/projects || exit
+#{
+#  wget https://github.com/ankitpokhrel/jira-cli/releases/download/v1.3.0/jira_1.3.0_linux_arm64.tar.gz
+#  tar -xzvf jira_1.3.0_linux_arm64.tar.gz
+#} || {
+#  echo "JIRA CLI setup failed."
+#  exit 1
+#}
 
 # Final Terminal Configurations
-export TERMINAL=tilix
-bash -c "$(wget -qO- https://git.io/vQgMr)" || echo "Final terminal configurations failed."
+# export TERMINAL=tilix
+# bash -c "$(wget -qO- https://git.io/vQgMr)" || echo "Final terminal configurations failed."
